version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/htdocs"
      - "/script"
    schedule:
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "production"

